### ISSUE TITLE
api returns 500 code

### ISSUE THREAD

**Issue by bnnnzzz** [sindresorhus/Forsvaretidag-Boxee#3]
The api you used returns a 500 code wich makes my boxee show an error

I demand this to be fixed really soon

**Comment by bnnnzzz** [comment]
@sindresorhus ping; this should be fixed soon

**Comment by sindresorhus** [comment]
This project is deprecated. I think the API used by this plugin is gone. Just uninstall the plugin.

Being demanding will get you nowhere in Open Source, or life.
